#!/bin/bash
#set -x

freq=${1-300}
echo "Setting frequence to $freq s"

dpi=${2-600}
echo "Setting resolution to $dpi dpi"

scanA3="epson2:libusb:001:007"

assets=assets
mkdir $assets

function scan {
  
  now=$(date +"%y.%m.%d-%H.%M.%S")
  
  # config scanner 
  # 1. scanimage -L
  # 2. copy the adress ( ex. epson2:libusb:001:006 ) to the -d param
  # remove d for one scan ?
  
  echo "scan A3 Epson ES-7000H      "
	#scanimage --format tiff --resolution $dpi -d $scanA3 -p > $assets/A3.tiff
  #rm $assets/A3.tiff

  rm $assets/last.txt
  echo "last scan $now" >> $assets/last.txt
}

#git pull origin 

scan

# while true; do 
#   scan
#   for (( i=$freq; i>0; i--)); do
#     sleep 1 &
#     printf "next shot in $i s \r"
#     wait    
#     printf "                  \r"
#   done
# done
