#!/bin/bash

#set -x
function allscan48 {
  rawDir=$1   # raw directory
  lnkDir=$2   # scan directory for latex (jpeg)
  pdfDir=$3   # pdf directory for print
  picDir=$4   # picture directory from mobiles
  
  now=$(date +"%y.%m.%d-%H.%M.%S")
 	
 	dpi=100
  
 	echo "scan 01             "
	scanimage --format tiff --mode Gray --resolution $dpi -d epson2:libusb:001:009 -p > $rawDir/01.tiff
	poster48 $1 $2 $3 $4
	
	echo "scan 02             "
	scanimage --format tiff --mode Gray --resolution $dpi -d hpaio:/usb/PSC_1600_series?serial=MY54PD10RQL0 -p > $rawDir/02.tiff
	poster48 $1 $2 $3 $4
	
	echo "scan 03             "
	scanimage --format tiff --mode Gray --resolution $dpi -d epson2:libusb:001:010 -p > $rawDir/03.tiff
	poster48 $1 $2 $3 $4
	
	echo "scan 04             "
	scanimage --format tiff --mode Gray --resolution $dpi -d snapscan:libusb:001:008 -p > $rawDir/04.tiff
  poster48 $1 $2 $3 $4
  
  echo "webcam 05           "
  streamer -f jpeg -s 1920x1080 -o $lnkDir/05-webcam.jpeg
  poster48 $1 $2 $3 $4
  
}
function poster48 {
  lastphoto48 $1 $2 $3 $4
  
  rawDir=$1   # raw directory
  lnkDir=$2   # scan directory for latex (jpeg)
  pdfDir=$3   # pdf directory for print
  picDir=$4   # picture directory from mobiles
  
  now=$(date +"%y.%m.%d-%H.%M.%S")
  
  echo "conversion          "
 	echo "$rawDir > jpeg > $lnkDir"
  mogrify -path $lnkDir/ -format jpeg "$rawDir*.tiff"
  
  echo "-> $now.pdf"
  echo "___"
  pdflatex tex_template/template_float_img.tex #>/dev/null
  mv template_float_img.pdf $pdfDir$now.pdf
}
function lastphoto48 {
  #pwd
  
  rawDir=$1   # raw directory
  lnkDir=$2   # scan directory for latex (jpeg)
  pdfDir=$3   # pdf directory for print
  picDir=$4   # picture directory from mobiles
  
  now=$(date +"%y.%m.%d-%H.%M.%S")
  
  find $picDir -name \.AppleDouble -exec rm -rf {} \;
  
  for pic in `find /home/pi/Documents/scan48/photo-inbox/ -iname "*.jpg" -type f -print -quit`
  do    
    echo "* new picture : $pic *"
    cp -f $pic $lnkDir"06.jpg"
    mv $pic "photo-archive/$(basename $(dirname $pic))/$(basename $pic)"
  done

}

cd ~/Documents/scan48

#while true; do
  clear
	allscan48 raw/ tex_template/links/ outbox/ photo-inbox/
#done

