#!/bin/bash
#set -x

freq=${1-5}
echo "Setting frequence to $freq s"

dpi=${2-100}
echo "Setting resolution to $dpi dpi"

fuzz=${3-40}
echo "Setting fuzz for keying to $fuzz%"


assets=assets
mkdir $assets

function scan {
  now=$(date +"%y.%m.%d-%H.%M.%S")
  
  # config scanner 
  # 1. scanimage -L
  # 2. copy the adress ( ex. epson2:libusb:001:006 ) to the -d param
  #
  
 	echo "scan A3 Epson ES-7000H      "
	scanimage --format tiff --mode Gray --resolution $dpi -d epson2:libusb:001:006 -p > $assets/A3.tiff
  
	convert -monitor -format png $assets/A3.tiff -auto-level -threshold 60%\
  -transparent white -negate $assets/A3.png
  
  echo "scan A4                     "
	scanimage --format tiff --resolution $dpi -d epson2:libusb:001:007 -p > $assets/A4.tiff
	convert -format png "$assets/A4.tiff" -fuzz $fuzz% -transparent "#00FF00" -modulate 100,0 $assets/A4.png
  
}

while true; do 
  scan
  for (( i=$freq; i>0; i--)); do
    sleep 1 &
    printf "next shot in $i s \r"
    wait    
    printf "                  \r"
  done
done
