#!/bin/bash
# set -x

function compilePDF (){

  now=$(date +"%y.%m.%d-%H.%M.%S")
  phantomjs rasterize.js "http://127.0.0.1/poster/" "$printbox/$now.pdf" 1 A3
  
  #convert "$assets/tmp.pdf" -modulate 100,0 $printbox/$now.pdf
}
function preprocessimages (){
  
  inbox=$1
  detox -rv $inbox
  
  for pic in `find $inbox -iname "*.*" -type f`
  do
    pic_name=$(basename $pic)
    
    now=$(date +"%Y%m%d_%H%M%S")
    
    convert $pic -format jpg -auto-orient -resize 800x800 -type GrayScaleMatte $import/$now.jpg
    mv $pic $archives/$pic_name
  done
}
function print {
  
  clear
  
  printinbox=$1
  printoutbox=$2
  
  printer=C224e_Labos                    # labos
  detox -rv $printinbox
  
  for step in `find $printinbox -iname "*.pdf" -type f`
  do
    ((printcount++))
    
    stepname=$(basename $step)
    archivePath=$printoutbox$stepname
    
    mv $step $archivePath # copy in outbox (archives)
    lpr -P $printer -o media=A3 -o ColorModel=KGray -o fit-to-page $archivePath

    printf "\t~ print \t $printcount \t\t $stepname \n\t_\t \t $(date +"%H.%M.%S")\n\n"
    
  done
}
function importFormShareFolder {
  source=$1
  target=$2
  
  filecount=$(find $source -type f ! -iname "*sync*" -exec printf '.' \; | wc -c  | tr -d ' ')
  
  if [[ $filecount > 0 ]]
  then
    detox -rv $source
    mv $source/*.jpg $target
    mv $source/*.png $target
  fi
}

# path
assets="assets/"
import=$assets"00-import"
printbox=$assets"01-printbox"
archives=$assets"02-archives"
replay=$assets"03-replay"

# params
interval=${1-20}
bgColor="#58bfff"
bgFuzz=20
printcount=0

inboxsources=( "/Users/benoit/Desktop/phone" "/Volumes/capture-MacBook-Pro-de-Brice-2" )

# main loop
while true; do
  
  # get from sources
  for inboxsource in "${inboxsources[@]}"; do
    importFormShareFolder $inboxsource $import/pictures/
  done
  
  # image processing
  preprocessimages $import/pictures/
  
  # print
  compilePDF
  print $printbox $archives"/printedpdf/"
  
  # wait
  for (( i=$interval; i>0; i--)); do
    sleep 1 &
    printf "next try in $i s \r"
    wait
    printf "                   \r"
  done
  clear

done