#!/bin/bash
# set -x

# helpers
function compilePDF (){

  now=$(date +"%y.%m.%d-%H.%M.%S")
  phantomjs rasterize.js $1 "$printbox/$now.pdf" A3 1 &
  
  #convert "$assets/tmp.pdf" -modulate 100,0 $printbox/$now.pdf
}
function preprocessimages (){
  
  inbox=$1
  detox -rv $inbox
  
  for pic in `find $inbox -iname "*.*" -type f`
  do
    pic_name=$(basename $pic)
    
    now=$(date +"%Y%m%d_%H%M%S")
    
    convert $pic -format jpg -auto-orient -resize 800x800 -type GrayScaleMatte $import/$now.jpg
    mv $pic $archives/$pic_name
  done
}
function print {
  
  printinbox=$1
  printoutbox=$2
  
  printer=_192_168_1_35                    # labos
  detox -rv $printinbox
  
  for step in `find $printinbox -iname "*.pdf" -type f`
  do
    ((printcount++))
    
    stepname=$(basename $step)
    archivePath=$printoutbox$stepname
    
    mv $step $archivePath # copy in outbox (archives)
    lpr -P $printer -o media=A3 -o ColorModel=KGray $archivePath #-o fit-to-page
    
    printf "\t~ print \t $printcount \t\t $stepname \n\t_\t \t $(date +"%H.%M.%S")\n\n"
    
  done
}
function importFormShareFolder {
  
  source=$1
  target=$2
  mediatype=$3
  
  # count files
  filecount=$(find $source -type f ! -iname "*sync" ! -iname "*.DS_Store" -exec printf '.' \; | wc -c  | tr -d ' ')
  sourcename=$(basename $source)
  sourcetype=${sourcename: -3 :4}

  # pre-processing
  
  if [[ $filecount > 0 ]]
  then
    detox -rv $source
    
    for type in "${mediatype[@]}"; do
      case "$sourcetype" in
        pic) 
          sourcetypename="picture"
        ;;
        sca) 
          sourcetypename="scanner"
        ;;
        * ) 
          sourcetypename="Not processed"
          mv $source/*.$type $target > /dev/null 2>&1
        ;;
      esac
    done
  fi
  printf "$sourcename \t $filecount file \t type : $sourcetypename ($sourcetype)\n\n"
}

# path
assets="assets/"
import=$assets"00-import"
printbox=$assets"01-printbox"
archives=$assets"02-archives"
replay=$assets"03-replay"
inboxsources=( "$import/photoNC" "$import/photoBV" "/Volumes/photo_canon" )

# params
interval=${1-10}
bgColor="#58bfff"
bgFuzz=20
printcount=0
mediatype=(jpg png md)

# main loop
while true; do
  clear
  echo "getsources ..."
  
  # get from sources
  for inboxsource in "${inboxsources[@]}"; do
    importFormShareFolder $inboxsource $import/pictures/ $mediatype
  done
  
  # image processing
  preprocessimages $import/pictures/
  
  # print
  compilePDF "http://192.168.1.34/poster/testcallback.html" &
  print $printbox $archives"/printedpdf/"
  say "print !"
  
  # wait
  for (( i=$interval; i>0; i--)); do
    sleep 1 &
    printf "next try in $i s \r"
    wait
    printf "                   \r"
  done
done