#!/bin/bash
# set -x

assets="assets/"

import=$assets"00-import"
printbox=$assets"01-printbox"
archives=$assets"02-archives"
replay=$assets"03-replay"

bgColor="#58bfff"
bgFuzz=20

new=false
printcount=0

function compilePDF (){

  now=$(date +"%y.%m.%d-%H.%M.%S")
  phantomjs poster/get.js >/dev/null
  convert assets/step.png -modulate 100,0 assets/01-printbox/$now.pdf  
}
function preprocessimages (){
  
  inbox=$1
  detox -rv $inbox
  
  for pic in `find $inbox -iname "*.*" -type f`
  do
    pic_name=$(basename $pic)
    
    now=$(date +"%Y%m%d_%H%M%S")
    
    convert $pic -format jpg -auto-orient -resize 800x800 -type GrayScaleMatte $import/$now.jpg
    mv $pic $archives/$pic_name
  done
}
function print {
  
  clear
  
  inbox=$1
  outbox=$2
  
  printer=C224e_Labos                    # labos
  detox -rv $inbox
  
  for step in `find $inbox -iname "*.pdf" -type f`
  do
    ((printcount++))
    
    stepname=$(basename $step)
    archivePath=$outbox$stepname
    
    mv $step $archivePath # copy in outbox (archives)
    lpr -P $printer -o media=A3 -o ColorModel=KGray -o fit-to-page $archivePath

    printf "\t~ print \t $printcount \t\t $stepname \n\t_\t \t $(date +"%H.%M.%S")\n\n"
    
  done
}
function importFormShareFolder {
  source=$1
  target=$2
  
  filecount=$(find $source -type f -exec printf '.' \; | wc -c  | tr -d ' ')
  
  if [[ $filecount > 0 ]]
  then
    detox -rv $source
    mv $source/* $target
  fi
}
interval=${1-5}

while true; do
  
  compilePDF
  print $printbox $archives"/printedpdf/"
  
  importFormShareFolder /Users/benoit/Desktop/test $import/pictures/
  preprocessimages $import/pictures/
  
  for (( i=$interval; i>0; i--)); do
    sleep 1 &
    printf "next try in $i s \r"
    wait    
    printf "                   \r"
  done
done